"""2_Update model Employee Client - gender

Revision ID: 33acdea24464
Revises: c0b12e4c1e5c
Create Date: 2022-12-29 18:49:50.776453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33acdea24464'
down_revision = 'c0b12e4c1e5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # hand start
    gender = postgresql.ENUM('MALE', 'FEMALE', name='gender')
    gender.create(op.get_bind())
    # hand end
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False))
    op.add_column('employee', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'gender')
    op.drop_column('client', 'gender')
    # ### end Alembic commands ###
    # hand start
    gender = postgresql.ENUM('MALE', 'FEMALE', name='gender')
    gender.drop(op.get_bind())
    # hand end