"""5_Update Service models - DateChanged

Revision ID: 3c952e9a3a9a
Revises: 3fd1b89e2c55
Create Date: 2023-01-06 19:03:09.904325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c952e9a3a9a'
down_revision = '3fd1b89e2c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('category', sa.Column('changed_at', sa.DateTime(), nullable=False))
    op.add_column('service_name', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('service_name', sa.Column('changed_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_name', 'changed_at')
    op.drop_column('service_name', 'created_at')
    op.drop_column('category', 'changed_at')
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
