"""8_Add filed Order.status

Revision ID: e640f031844c
Revises: efa46f5b44ca
Create Date: 2023-01-10 11:36:24.298984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e640f031844c'
down_revision = 'efa46f5b44ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # hand start
    status = postgresql.ENUM('WAIT', 'CANCEL', 'PAID', 'SUCCESS', 'PROC_RETURN', 'RETURN', name='statusorder')
    status.create(op.get_bind())
    # hand end
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.Enum('WAIT', 'CANCEL', 'PAID', 'SUCCESS', 'PROC_RETURN', 'RETURN', name='statusorder'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
    # hand start
    status = postgresql.ENUM('WAIT', 'CANCEL', 'PAID', 'SUCCESS', 'PROC_RETURN', 'RETURN', name='statusorder')
    status.drop(op.get_bind())
    # hand end
