"""10_Add field OrderModel.service

Revision ID: a772a83ce6bc
Revises: 362ae7cdf1cd
Create Date: 2023-01-10 17:45:17.977720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a772a83ce6bc'
down_revision = '362ae7cdf1cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('service_id', sa.Integer(), nullable=True))
    # hand - fk_order_service_name
    op.create_foreign_key('fk_order_service_name', 'order', 'service_name', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # hand - fk_order_service_name
    op.drop_constraint('fk_order_service_name', 'order', type_='foreignkey')
    op.drop_column('order', 'service_id')
    # ### end Alembic commands ###
