"""11_Add index for FK

Revision ID: 15ecb33bbf06
Revises: a772a83ce6bc
Create Date: 2023-01-28 15:23:26.542136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ecb33bbf06'
down_revision = 'a772a83ce6bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_offer_link_employee_id'), 'offer_link', ['employee_id'], unique=False)
    op.drop_constraint('order_detail_order_id_key', 'order_detail', type_='unique')
    op.create_index(op.f('ix_order_detail_order_id'), 'order_detail', ['order_id'], unique=True)
    op.create_index(op.f('ix_service_name_category_id'), 'service_name', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_name_category_id'), table_name='service_name')
    op.drop_index(op.f('ix_order_detail_order_id'), table_name='order_detail')
    op.create_unique_constraint('order_detail_order_id_key', 'order_detail', ['order_id'])
    op.drop_index(op.f('ix_offer_link_employee_id'), table_name='offer_link')
    # ### end Alembic commands ###
